name: deal_ml
description: Uma demonstração de Google ML Vision

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.7+1
  google_ml_kit: ^0.11.0
  keep_screen_on: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
